apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: microservices
  labels:
    app: ai-service
spec:
  selector:
    app: ai-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
