apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
