apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices
type: Opaque
stringData:
  mysql-root-password: root
  postgres-password: root
  keycloak-admin-password: admin
